fix(cli): fix ImportError when executing gas CLI in python3.6 and 3.7
Root Cause:
`tensorbay/cli/utility.py` import `Literal` from `typing`, but `Literal`
is added to `typing` in python3.8, which causes the `ImportError`:
```python
ImportError: cannot import name 'Literal'
```

Solution:
Import `Literal` from `typing_extensions`

PR Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/pull/575