fix(client): fix the TypeError when put Dataset in multiprocess pool
Root Cause:
The `threading.Lock` object cannot be pickled. The `threading.Lock` is
widely used in `Dataset` to avoid sending redundant requests. So that
putting `Dataset` in multiprocess pool will hit the TypeError caused by
`threading.Lock`:
```python
TypeError: cannot pickle '_thread.lock' object
```

Solution:
Remove all the `theading.Lock` member in `Dataset`, and use a lock pool
to dynamicly create `threading.Lock` when sending request.

PR Closed: https://github.com/Graviti-AI/tensorbay-python-sdk/pull/545